"""AVIIN ATS company-device monitoring agent (Windows).

Scope, deliberately: active-window/idle time + browser URL history on
company-issued Windows laptops only. Explicitly does NOT capture
keystrokes, screenshots, or screen content, and does not run on personal
devices — see CLAUDE.md's "Device Monitoring" section for why.

Always shows a system tray icon while running (transparency requirement —
this agent never runs silently/hidden). Requires an enrollment code
generated by the recruiter themselves from the ATS web UI after they
explicitly consent; there is no way for anyone else to enroll a device on
someone's behalf.

Usage:
    python aviin_device_agent.py enroll <api_base_url> <CODE>
    python aviin_device_agent.py run
    python aviin_device_agent.py install-autostart
"""
import ctypes
import json
import os
import platform
import shutil
import socket
import sqlite3
import sys
import tempfile
import threading
import time
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

import requests

AGENT_VERSION = "0.1.0"
APP_DIR = Path(os.environ.get("LOCALAPPDATA", tempfile.gettempdir())) / "AviinDeviceAgent"
CONFIG_PATH = APP_DIR / "config.json"

SAMPLE_INTERVAL_SECONDS = 5
FLUSH_INTERVAL_SECONDS = 300
IDLE_THRESHOLD_SECONDS = 120

# ── Config ────────────────────────────────────────────────────────────────

def load_config() -> dict:
    if CONFIG_PATH.exists():
        return json.loads(CONFIG_PATH.read_text())
    return {}


def save_config(cfg: dict) -> None:
    APP_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(json.dumps(cfg, indent=2))


def device_fingerprint() -> str:
    # Stable per-machine id (not tied to any one network adapter), stored
    # once and reused — avoids re-enrolling as a "new device" on every run.
    cfg = load_config()
    if cfg.get("device_fingerprint"):
        return cfg["device_fingerprint"]
    fp = str(uuid.uuid4())
    cfg["device_fingerprint"] = fp
    save_config(cfg)
    return fp


# ── Enrollment ───────────────────────────────────────────────────────────

def enroll(api_base: str, code: str) -> None:
    resp = requests.post(
        f"{api_base.rstrip('/')}/device-monitoring/enroll",
        json={
            "token": code,
            "hostname": socket.gethostname(),
            "os": f"{platform.system()} {platform.release()}",
            "device_fingerprint": device_fingerprint(),
            "agent_version": AGENT_VERSION,
        },
        timeout=15,
    )
    if not resp.ok:
        print(f"Enrollment failed: {resp.status_code} {resp.text}")
        sys.exit(1)
    data = resp.json()
    cfg = load_config()
    cfg.update({
        "api_base": api_base.rstrip("/"),
        "device_id": data["device_id"],
        "device_api_key": data["device_api_key"],
    })
    save_config(cfg)
    print(f"Enrolled successfully. Device ID: {data['device_id']}")


# ── Active window + idle tracking (Windows only; no keystroke/content capture) ──

def get_idle_seconds() -> float:
    class LASTINPUTINFO(ctypes.Structure):
        _fields_ = [("cbSize", ctypes.c_uint), ("dwTime", ctypes.c_uint)]

    info = LASTINPUTINFO()
    info.cbSize = ctypes.sizeof(LASTINPUTINFO)
    ctypes.windll.user32.GetLastInputInfo(ctypes.byref(info))
    millis = ctypes.windll.kernel32.GetTickCount() - info.dwTime
    return millis / 1000.0


def get_active_window():
    """Returns (app_name, window_title) for the foreground window.
    Window title only, never window content — same category of signal as
    every disclosed activity-monitoring tool (Time Doctor, ActivTrak, etc.)."""
    import win32gui
    import win32process
    import psutil

    hwnd = win32gui.GetForegroundWindow()
    if not hwnd:
        return None, None
    title = win32gui.GetWindowText(hwnd)
    try:
        _, pid = win32process.GetWindowThreadProcessId(hwnd)
        app_name = psutil.Process(pid).name()
    except Exception:
        app_name = None
    return app_name, title


# ── Browser history (Chrome/Edge; Chromium's SQLite History file) ──────────
# The file is locked while the browser runs, so we copy it before reading —
# a standard, well-known technique for this exact reason (not an evasion of
# anything; the browser just holds an exclusive lock).

CHROME_EPOCH = datetime(1601, 1, 1, tzinfo=timezone.utc)


def _chrome_time_to_dt(chrome_us: int) -> datetime:
    return CHROME_EPOCH + timedelta(microseconds=chrome_us)


def _dt_to_chrome_time(dt: datetime) -> int:
    return int((dt - CHROME_EPOCH).total_seconds() * 1_000_000)


def _browser_history_paths():
    local = Path(os.environ.get("LOCALAPPDATA", ""))
    return {
        "chrome": local / "Google" / "Chrome" / "User Data" / "Default" / "History",
        "edge": local / "Microsoft" / "Edge" / "User Data" / "Default" / "History",
    }


def read_browser_history(since: datetime):
    """Yields (browser, url, title, visited_at) for visits after `since`."""
    for browser, path in _browser_history_paths().items():
        if not path.exists():
            continue
        tmp_copy = Path(tempfile.gettempdir()) / f"aviin_agent_{browser}_history_copy.db"
        try:
            shutil.copy2(path, tmp_copy)
            conn = sqlite3.connect(str(tmp_copy))
            since_chrome = _dt_to_chrome_time(since)
            rows = conn.execute(
                "SELECT url, title, last_visit_time FROM urls WHERE last_visit_time > ? ORDER BY last_visit_time ASC",
                (since_chrome,),
            ).fetchall()
            conn.close()
            for url, title, ts in rows:
                yield browser, url, title, _chrome_time_to_dt(ts)
        except Exception as e:
            print(f"[{browser}] history read skipped: {e}")
        finally:
            tmp_copy.unlink(missing_ok=True)


# ── Reporting ────────────────────────────────────────────────────────────

def post_batch(cfg: dict, path: str, payload: dict) -> bool:
    try:
        resp = requests.post(
            f"{cfg['api_base']}{path}",
            json=payload,
            headers={"X-Device-Key": cfg["device_api_key"]},
            timeout=15,
        )
        return resp.ok
    except Exception as e:
        print(f"[report] {path} failed: {e}")
        return False


# ── Tray icon (always visible while the agent runs — transparency) ─────────

def _make_tray_icon():
    from PIL import Image, ImageDraw
    img = Image.new("RGB", (64, 64), "white")
    d = ImageDraw.Draw(img)
    d.ellipse((8, 8, 56, 56), fill=(37, 99, 235))
    d.text((22, 24), "A", fill="white")
    return img


def run_tray(stop_event: threading.Event):
    import pystray
    icon = pystray.Icon(
        "aviin_device_agent",
        _make_tray_icon(),
        "AVIIN Device Monitoring — Active",
        menu=pystray.Menu(
            pystray.MenuItem("AVIIN Device Monitoring is active", None, enabled=False),
            pystray.MenuItem("Quit", lambda: (stop_event.set(), icon.stop())),
        ),
    )
    icon.run()


# ── Main loop ────────────────────────────────────────────────────────────

def run():
    cfg = load_config()
    if not cfg.get("device_api_key"):
        print("Not enrolled. Run: python aviin_device_agent.py enroll <api_base_url> <CODE>")
        sys.exit(1)

    stop_event = threading.Event()
    tray_thread = threading.Thread(target=run_tray, args=(stop_event,), daemon=True)
    tray_thread.start()

    segments = []
    cur_app, cur_title, cur_start, cur_idle = None, None, None, False
    last_flush = time.monotonic()
    last_browsing_since = datetime.now(timezone.utc) - timedelta(minutes=5)

    print("AVIIN Device Monitoring agent running. Tray icon active.")
    while not stop_event.is_set():
        idle_secs = get_idle_seconds()
        is_idle = idle_secs >= IDLE_THRESHOLD_SECONDS
        app_name, title = get_active_window() if not is_idle else (cur_app, "Idle")
        now = datetime.now(timezone.utc)

        if app_name != cur_app or is_idle != cur_idle:
            if cur_app is not None and cur_start is not None:
                segments.append({
                    "app_name": cur_app, "window_title": cur_title,
                    "started_at": cur_start.isoformat(), "ended_at": now.isoformat(),
                    "is_idle": cur_idle,
                })
            cur_app, cur_title, cur_start, cur_idle = app_name, title, now, is_idle

        if time.monotonic() - last_flush >= FLUSH_INTERVAL_SECONDS:
            if segments:
                if post_batch(cfg, "/device-monitoring/heartbeat", {"entries": segments}):
                    segments = []

            browsing_entries = [
                {"url": url, "page_title": title, "browser": browser, "visited_at": visited_at.isoformat()}
                for browser, url, title, visited_at in read_browser_history(last_browsing_since)
            ]
            if browsing_entries:
                if post_batch(cfg, "/device-monitoring/browsing", {"entries": browsing_entries}):
                    last_browsing_since = now
            else:
                last_browsing_since = now
            last_flush = time.monotonic()

        stop_event.wait(SAMPLE_INTERVAL_SECONDS)


def install_autostart():
    import winreg
    exe = sys.executable
    script = os.path.abspath(__file__)
    key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\Microsoft\Windows\CurrentVersion\Run", 0, winreg.KEY_SET_VALUE)
    winreg.SetValueEx(key, "AviinDeviceAgent", 0, winreg.REG_SZ, f'"{exe}" "{script}" run')
    winreg.CloseKey(key)
    print("Auto-start installed (runs at login, from your own user account only).")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)
    cmd = sys.argv[1]
    if cmd == "enroll" and len(sys.argv) == 4:
        enroll(sys.argv[2], sys.argv[3])
    elif cmd == "run":
        run()
    elif cmd == "install-autostart":
        install_autostart()
    else:
        print(__doc__)
